### ISSUE TITLE
RR Downtown uses a custom beverage producer

### ISSUE THREAD

**Issue by drewbrew** [hsv-dot-beer/hsvdotbeer#334]
```
Processing Rocket Republic Downtown Huntsville
Traceback (most recent call last):
  File "./manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/code/tap_list_providers/management/commands/parsedigitalpour.py", line 22, in handle
    tap_list_provider.handle_venue(venue)
  File "/code/tap_list_providers/parsers/digitalpour.py", line 66, in handle_venue
    parsed_manufacturer = self.parse_manufacturer(entry)
  File "/code/tap_list_providers/parsers/digitalpour.py", line 207, in parse_manufacturer
    raise ValueError(f"Unknown producer type {producer}")
ValueError: Unknown producer type {'$type': 'BeerDashboard.Common.Models.CustomBeverageModels.CustomBeverageProducer, BeerDashboard.Common', 'CompanyName': 'Rocket Republic Brewing Company', 'ProducerUrl': None, 'CultureSpecificProducerNames': {}, 'CultureSpecificLocationNames': {}, 'ProducerName': 'Rocket Republic Brewing Company', 'SimplifiedProducerName': 'rocket republic brewing company', 'CultureAwareProducerName': 'Rocket Republic Brewing Company', 'CultureAwareLocation': None, 'Id': '5d657d943527260064257abf', 'FullProducerName': None, 'Location': None, 'ProducersUrl': None, 'LogoImageUrl': None, 'TwitterName': None, 'Latitude': 0.0, 'Longitude': 0.0, 'DefaultKegSize': 0.0, 'DefaultKegCoupler': None, 'CompanyId': None, 'IsAmateur': False, 'AlternateLocations': [], 'LatestCertificate': None}
```

**Comment by drewbrew** [comment]
```json
{
    "Id": "5e3dcd703527260c18945688",
    "MenuItemDisplayDetail": {
        "$type": "BeerDashboard.Common.Models.Tap, BeerDashboard.Common",
        "BeverageType": null,
        "TapType": "CO2",
        "NonRotating": false,
        "HasMeasuringSystem": false,
        "ParentTapId": null,
        "Material": null,
        "LineDrop": null,
        "LineLength": null,
        "LineDiameter": null,
        "CO2Mix": null,
        "NitroMix": null,
        "PSI": null,
        "Id": "5db43cfe35272618745ba574",
        "CompanyId": "5d657d943527260064257abf",
        "CompanyName": "Rocket Republic Brewing Company",
        "LocationId": "2",
        "LocationName": "Downtown",
        "ItemType": "Tap",
        "DisplayName": "20",
        "DisplayOrder": 20,
        "DisplayLogoUrl": null,
        "DisplayGroup": null,
        "CostCenter": null,
        "NotInUse": false,
        "StorageLocation": {
            "CompanyId": "5d657d943527260064257abf",
            "CompanyName": null,
            "LocationId": "2",
            "LocationName": "Downtown",
            "IsUsable": true,
            "DefaultKegLocation": true,
            "TemperatureSensorId": null,
            "Temperature": 0.0,
            "Id": "5db43bd93527260b8c01b124",
            "StorageLocationName": "Cooler"
        },
        "ProductId": null,
        "MeasuringSystemMappingId": null,
        "EventTableId": null,
        "TemperatureSensorId": null,
        "Temperature": 0.0,
        "IsDirty": false
    },
    "MenuItemProductDetail": {
        "$type": "BeerDashboard.Common.Models.Keg, BeerDashboard.Common",
        "KegSize": 661.0,
        "KegType": "CO2",
        "Coupler": "US Sankey (D)",
        "BatchId": null,
        "DateKegged": null,
        "KegId": null,
        "InitialOuncesConsumed": 0.0,
        "SamplesPoured": 0,
        "SampleSize": 0.0,
        "OuncesConsumed": 0.0,
        "PercentFull": 1.0,
        "UseMeasuredValues": false,
        "PosReportedOuncesConsumed": 0.0,
        "PosReportedPercentFull": 0.0,
        "MeasuredOuncesConsumed": 0.0,
        "MeasuredPercentFull": 0.0,
        "ShellReturnedToDistributor": false,
        "ShellReturnDate": null,
        "DaysOn": 134,
        "TimeOn": 99237.55112782499,
        "AllowedTaps": null,
        "PercentConsumedBySamples": null,
        "EstimatedOzLeft": 661.0,
        "HasRestrictions": false,
        "RestrictedReplacementsList": null,
        "EstimatedKegLeftDuration": "00:00:00",
        "AvailableInBottles": false,
        "MoreKegsAvailable": false,
        "Id": "98f26e7e-b6f7-4996-9853-b3109f48be70",
        "BeverageType": "Custom",
        "Beverage": {
            "$type": "BeerDashboard.Common.Models.CustomBeverageModels.CustomBeverage, BeerDashboard.Common",
            "BeverageName": "Rotating Hard Seltzer (Ask your Beertender!)",
            "BeverageProducer": {
                "$type": "BeerDashboard.Common.Models.CustomBeverageModels.CustomBeverageProducer, BeerDashboard.Common",
                "CompanyName": "Rocket Republic Brewing Company",
                "ProducerUrl": null,
                "CultureSpecificProducerNames": {},
                "CultureSpecificLocationNames": {},
                "ProducerName": "Rocket Republic Brewing Company",
                "SimplifiedProducerName": "rocket republic brewing company",
                "CultureAwareProducerName": "Rocket Republic Brewing Company",
                "CultureAwareLocation": null,
                "Id": "5d657d943527260064257abf",
                "FullProducerName": null,
                "Location": null,
                "ProducersUrl": null,
                "LogoImageUrl": null,
                "TwitterName": null,
                "Latitude": 0.0,
                "Longitude": 0.0,
                "DefaultKegSize": 0.0,
                "DefaultKegCoupler": null,
                "CompanyId": null,
                "IsAmateur": false,
                "AlternateLocations": [],
                "LatestCertificate": null
            },
            "BeverageStyle": null,
            "CultureAwareBeverageName": "Rotating Hard Seltzer (Ask your Beertender!)",
            "FullProducerList": "Rocket Republic Brewing Company",
            "ResolvedLogoImageUrl": "https://s3-us-west-2.amazonaws.com/wineslingrbarlogos/5d657d943527260064257abf.png",
            "FullStyleName": "Hard Seltzer",
            "ExpandedStyleName": "Hard Seltzer",
            "StyleColor": 16578037,
            "CustomBeverageName": "Rotating Hard Seltzer (Ask your Beertender!)",
            "CompanyId": "5d657d943527260064257abf",
            "CompanyName": "Rocket Republic Brewing Company",
            "CompanyLogoUrl": "https://s3-us-west-2.amazonaws.com/wineslingrbarlogos/5d657d943527260064257abf.png",
            "BeverageDescription": "Hard Seltzer",
            "BeverageColor": 16578037,
            "Abv": 5.0,
            "Id": "5eed20643527260ac86cb944",
            "BeverageType": null,
            "BeverageProducerId": null,
            "BeverageStyleId": null,
            "LogoImageUrl": null,
            "CO2Content": null,
            "CaloriesPerOz": null,
            "CustomDescription": null,
            "CustomStyle": null,
            "LatestAward": null,
            "LatestCertificate": null
        },
        "DateProduced": "0001-01-01T00:00:00Z",
        "Year": 2020,
        "BeverageCategory": null,
        "BeverageCategoryLogoUrl": null,
        "Attributes": [],
        "CustomBeverageIcon": null,
        "HasVintage": false,
        "Prices": [
            {
                "Id": "FL",
                "Size": 4.0,
                "Price": 2.0,
                "DisplayName": "4oz",
                "DisplaySize": 4.0,
                "PosModifier": "flight",
                "DisplayOrderInPos": null,
                "SizeInPos": null,
                "UPCCode": null,
                "CostCenter": null,
                "IsUnitPrice": false,
                "Quantity": 1,
                "Glassware": "Snifter 2 (Small)",
                "DisplayOnMenu": true,
                "Deactivated": false,
                "CanToGo": false,
                "Preferred": false
            },
            {
                "Id": "A",
                "Size": 7.5,
                "Price": 5.0,
                "DisplayName": "8oz",
                "DisplaySize": 8.0,
                "PosModifier": "8oz",
                "DisplayOrderInPos": null,
                "SizeInPos": null,
                "UPCCode": null,
                "CostCenter": null,
                "IsUnitPrice": false,
                "Quantity": 1,
                "Glassware": "Pilsner 3 (Small)",
                "DisplayOnMenu": false,
                "Deactivated": false,
                "CanToGo": false,
                "Preferred": false
            },
            {
                "Id": "B",
                "Size": 11.5,
                "Price": 4.0,
                "DisplayName": "12oz",
                "DisplaySize": 12.0,
                "PosModifier": "12oz",
                "DisplayOrderInPos": null,
                "SizeInPos": null,
                "UPCCode": null,
                "CostCenter": null,
                "IsUnitPrice": false,
                "Quantity": 1,
                "Glassware": "Goblet",
                "DisplayOnMenu": true,
                "Deactivated": false,
                "CanToGo": false,
                "Preferred": false
            },
            {
                "Id": "G",
                "Size": 12.0,
                "Price": 5.0,
                "DisplayName": "12oz can",
                "DisplaySize": 12.0,
                "PosModifier": "12oz can",
                "DisplayOrderInPos": null,
                "SizeInPos": null,
                "UPCCode": null,
                "CostCenter": null,
                "IsUnitPrice": false,
                "Quantity": 1,
                "Glassware": "Beer Can",
                "DisplayOnMenu": false,
                "Deactivated": false,
                "CanToGo": false,
                "Preferred": false
            },
            {
                "Id": "C",
                "Size": 15.5,
                "Price": 6.0,
                "DisplayName": "16oz",
                "DisplaySize": 16.0,
                "PosModifier": "main glass",
                "DisplayOrderInPos": null,
                "SizeInPos": null,
                "UPCCode": null,
                "CostCenter": null,
                "IsUnitPrice": false,
                "Quantity": 1,
                "Glassware": "Nonic",
                "DisplayOnMenu": true,
                "Deactivated": false,
                "CanToGo": false,
                "Preferred": false
            },
            {
                "Id": "D",
                "Size": 34.0,
                "Price": 1.0,
                "DisplayName": "32oz",
                "DisplaySize": 32.0,
                "PosModifier": "crowler",
                "DisplayOrderInPos": null,
                "SizeInPos": null,
                "UPCCode": null,
                "CostCenter": null,
                "IsUnitPrice": false,
                "Quantity": 1,
                "Glassware": "Beer Can",
                "DisplayOnMenu": false,
                "Deactivated": false,
                "CanToGo": false,
                "Preferred": false
            },
            {
                "Id": "E",
                "Size": 35.2,
                "Price": 1.0,
                "DisplayName": "32oz",
                "DisplaySize": 32.0,
                "PosModifier": "32oz growler",
                "DisplayOrderInPos": null,
                "SizeInPos": null,
                "UPCCode": null,
                "CostCenter": null,
                "IsUnitPrice": false,
                "Quantity": 1,
                "Glassware": "Grenade",
                "DisplayOnMenu": false,
                "Deactivated": false,
                "CanToGo": false,
                "Preferred": false
            },
            {
                "Id": "F",
                "Size": 70.4,
                "Price": 1.0,
                "DisplayName": "64oz",
                "DisplaySize": 64.0,
                "PosModifier": "64oz growler",
                "DisplayOrderInPos": null,
                "SizeInPos": null,
                "UPCCode": null,
                "CostCenter": null,
                "IsUnitPrice": false,
                "Quantity": 1,
                "Glassware": "Growler",
                "DisplayOnMenu": false,
                "Deactivated": false,
                "CanToGo": false,
                "Preferred": false
            }
        ],
        "EventPrices": null,
        "EventPricesActive": false,
        "EventId": null,
        "EventName": null,
        "EventExpires": null,
        "DateAdded": "2020-06-19T20:33:45.193Z",
        "DoNotUse": false,
        "ProductFinished": false,
        "ReplacesBeverageIds": [],
        "BeverageNameWithVintage": "Rotating Hard Seltzer (Ask your Beertender!)",
        "FullBeverageName": "Rocket Republic Brewing Company Rotating Hard Seltzer (Ask your Beertender!)",
        "FullProducerList": "Rocket Republic Brewing Company",
        "FullStyleName": "Hard Seltzer",
        "OverrideableFullStyleName": "Hard Seltzer",
        "EventItem": false,
        "ReplaceableItem": false
    },
    "Active": true,
    "EstimatedDatePutOn": null,
    "DatePutOn": "2020-02-07T20:50:07.986Z",
    "DatePulledOff": null,
    "QuantityOnTap": 0,
    "LastRefreshDateTime": "2020-06-19T20:34:12.359Z"
}
```
