### ISSUE TITLE
Digitalpour parsing is broken 

### ISSUE THREAD

**Issue by drewbrew** [hsv-dot-beer/hsvdotbeer#441]
```
# /root/.local/share/virtualenvs/code-_Py8Si6I/bin/python manage.py parsedigitalpour
Processing Straight to Ale
Processing Madison Taproom
Processing Old Town Beer Exchange
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "venue_tapnumber"
DETAIL:  Key (venue_id, tap_number)=(4, 13) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/code/tap_list_providers/management/commands/parsedigitalpour.py", line 21, in handle
    timestamp = tap_list_provider.handle_venue(venue)
  File "/code/tap_list_providers/parsers/digitalpour.py", line 128, in handle_venue
    tap.save()
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "venue_tapnumber"
DETAIL:  Key (venue_id, tap_number)=(4, 13) already exists.
```

**Comment by drewbrew** [comment]
They have both Snake Handler and Ferus Imperial Milk Stout on tap 13
